### ISSUE TITLE
[Windows Wallet] recipient () does not refer to any valid address

### ISSUE THREAD

**Issue by Darkwinde** [DeFiCh/ain#203]
Hi all,

I tried to swap DFI to BTC/ETH/USDT in DEX and get the error "recipient () does not refer to any valid address"

<img src="https://user-images.githubusercontent.com/7759961/106071119-0bc3a000-6106-11eb-8a30-d7d7c2d1090b.PNG" width="75%">

Wallet: 2.1.13
Type: Windows 10 - 10.0.19042

App Log: [recipient_error.log](https://github.com/DeFiCh/ain/files/5883915/recipient_error.log)
```
[2021-01-28 00:36:38.039] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"7307471533660646\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:36:40.036] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"19090923680263283\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:36:42.036] [IPC-RENDERER-error] [isBlockchainStarted] {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:101767)\n    at e.exports (file:///vendor.d5241135cfdddf9a65b1.js:8:104168)\n    at XMLHttpRequest.f.onreadystatechange (file:///vendor.d5241135cfdddf9a65b1.js:8:97988)","config":{"url":"/","method":"post","data":"{\"jsonrpc\":\"1.0\",\"id\":\"6279281580117477\",\"method\":\"getblockchaininfo\",\"params\":[]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","cache-control":"no-cache"},"baseURL":"http://VbdLrwkL:a190c202d4321c8ef4f108c5db0cb9f715556e7bf254c55483118644611275e3@127.0.0.1:8555","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
[2021-01-28 00:37:04.887] [IPC-RENDERER-info] [handleTestPoolSwapTo] "Starting"
[2021-01-28 00:37:11.277] [IPC-RENDERER-info] [handlePoolSwap] "Starting"
[2021-01-28 00:37:11.314] [IPC-RENDERER-info] [handlePoolSwap] "1. Address  Amount 0"
[2021-01-28 00:37:11.317] [IPC-RENDERER-info] [handlePoolSwap] "Account to Account"
[2021-01-28 00:37:11.319] [IPC-RENDERER-info] [handlePoolSwap] "UTXOs to Account"
[2021-01-28 00:37:11.337] [IPC-RENDERER-error]  "Request failed with status code 500"
[2021-01-28 00:37:44.411] [IPC-RENDERER-info] [handleTestPoolSwapTo] "Starting"
[2021-01-28 00:37:55.788] [IPC-RENDERER-info] [handlePoolSwap] "Starting"
[2021-01-28 00:37:55.818] [IPC-RENDERER-info] [handlePoolSwap] "1. Address  Amount 0"
[2021-01-28 00:37:55.819] [IPC-RENDERER-info] [handlePoolSwap] "Account to Account"
[2021-01-28 00:37:55.820] [IPC-RENDERER-info] [handlePoolSwap] "UTXOs to Account"
[2021-01-28 00:37:55.844] [IPC-RENDERER-error]  "Request failed with status code 500"
```

**Comment by Darkwinde** [comment]
Used wrong repro to report the bug. Transferred to: https://github.com/DeFiCh/app/issues/416

Sorry for any inconvenience.
