### ISSUE TITLE
v4-Beta6 crashes without reindex

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#2241]
## Summary

compile v4-beta6 (commit a84c51d4005eb640b966a300a3b26f438478ca56) and run it on a data folder from beta5. node crashes on init with 
```
2023-07-27T14:29:20Z [ain_evm::services] Starting tokio waiter
2023-07-27T14:29:20Z [ain_evm::storage::traits] Restoring transaction_data.bin from disk
2023-07-27T14:29:27Z [ain_evm::storage::traits] Restoring block_map.bin from disk
2023-07-27T14:29:27Z [ain_evm::storage::traits] Restoring latest_block_data.bin from disk
2023-07-27T14:29:27Z [ain_evm::storage::traits] Restoring block_data.bin from disk
thread '<unnamed>' panicked at 'Error loading blocks data: BincodeError(Custom("invalid length 0, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 32] bytes"))', ain-evm/src/storage/data_handler.rs:72:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::expect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1046:23
   4: ain_evm::storage::data_handler::BlockchainDataHandler::restore
             at ./lib/ain-evm/src/storage/data_handler.rs:72:17
   5: ain_evm::storage::Storage::restore
             at ./lib/ain-evm/src/storage/mod.rs:46:38
   6: ain_evm::evm::EVMServices::new
             at ./lib/ain-evm/src/evm.rs:77:36
   7: ain_evm::services::Services::new
             at ./lib/ain-evm/src/services.rs:60:27
   8: <ain_evm::services::SERVICES as core::ops::deref::Deref>::deref::__static_ref_initialize
             at ./lib/ain-evm/src/services.rs:27:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  10: spin::once::Once<T>::call_once
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin-0.5.2/src/once.rs:110:50
  11: lazy_static::lazy::Lazy<T>::get
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/core_lazy.rs:21:9
  12: <ain_evm::services::SERVICES as core::ops::deref::Deref>::deref::__stability
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/lib.rs:142:21
  13: <ain_evm::services::SERVICES as core::ops::deref::Deref>::deref
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/lib.rs:144:17
  14: ain_grpc::init_services
             at ./lib/ain-grpc/src/lib.rs:59:14
  15: ain_rs_exports::core::ain_rs_init_core_services
             at ./lib/ain-rs-exports/src/core.rs:15:5
  16: ain_rs_exports::ffi::_::__ain_rs_init_core_services::__ain_rs_init_core_services
             at ./lib/ain-rs-exports/src/lib.rs:19:12
  17: ain_rs_exports::ffi::_::__ain_rs_init_core_services::{{closure}}
             at ./lib/ain-rs-exports/src/lib.rs:8:1
  18: cxx::unwind::prevent_unwind
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cxx-1.0.97/src/unwind.rs:23:15
  19: cxxbridge1$ain_rs_init_core_services
             at ./lib/ain-rs-exports/src/lib.rs:19:71
  20: _ZZ11AppInitMainR14InitInterfacesENK3$_8clEv
             at ./src/init.cpp:1932:28
  21: _Z11AppInitMainR14InitInterfaces
             at ./src/init.cpp:1932:28
  22: _ZL7AppInitiPPc
             at ./src/defid.cpp:171:16
  23: main
             at ./src/defid.cpp:201:13
```
(when running it with RUST_BACKTRACE=1) 

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: v4-beta6
- Block height on bug if applicable: NA
- TX or TX type on bug if applicable:  NA
- OS with version: macOS Ventura 13.2.1
- Any other relevant environment info:  using data folder from running beta5

**Comment by kuegi** [comment]
fixed in beta6_fix branch 👍
