### ISSUE TITLE
4.0.0 beta7  'tokio-runtime-worker' panicked at 'Block 5130 out of range' even after complete data wipe

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#2274]
## Summary

- node failed syncing with `ERROR: ConnectTip: ConnectBlock 0ef56baa54324f51a674ae12dfac3487d9406e9efa60288fd4a38ffc555befc6 failed, EVM block rejected for invalid nonce. Address 0x3637…adec nonce 12, signed_tx nonce: 13`
- even after complete wipe of the changi folder (except for wallets), the log gets filled with panicking:
```
'tokio-runtime-worker' panicked at 'Block 5130 out of range', ain-evm/src/block.rs:166:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: ain_evm::block::BlockService::fee_history::{{closure}}
             at ./lib/ain-evm/src/block.rs:166:40
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:1000:21
   4: ain_evm::block::BlockService::fee_history
             at ./lib/ain-evm/src/block.rs:164:17
   5: <ain_grpc::rpc::eth::MetachainRPCModule as ain_grpc::rpc::eth::MetachainRPCServer>::fee_history
             at ./lib/ain-grpc/src/rpc/eth.rs:777:32
   6: ain_grpc::rpc::eth::MetachainRPCServer::into_rpc::{{closure}}
             at ./lib/ain-grpc/src/rpc/eth.rs:30:1
   7: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_method::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-core-0.15.1/src/server/rpc_module.rs:567:81
   8: jsonrpsee_http_server::server::execute_call::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-http-server-0.15.1/src/server.rs:846:15
   9: jsonrpsee_http_server::server::process_single_request::{{closure}}::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-http-server-0.15.1/src/server.rs:813:49
  10: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:283:9
  11: jsonrpsee_http_server::server::process_single_request::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-http-server-0.15.1/src/server.rs:816:3
  12: jsonrpsee_http_server::server::process_validated_request::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-http-server-0.15.1/src/server.rs:647:52
  13: jsonrpsee_http_server::server::Server<M>::start::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-http-server-0.15.1/src/server.rs:519:9
  14: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:491:35
  15: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:297:43
  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:161:21
  17: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:137:16
  18: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:120:28
  19: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/proto/h1/dispatch.rs:424:9
  20: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/conn.rs:986:47
  21: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/conn.rs:1046:30
  22: <hyper::common::drain::Watching<F,FN> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/common/drain.rs:95:36
  23: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/server/server.rs:763:36
  24: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  26: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  27: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  29: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  30: ___rust_try
  31: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  32: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  33: tokio::runtime::task::harness::poll_future
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  34: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  35: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  36: tokio::runtime::task::raw::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  37: tokio::runtime::task::raw::RawTask::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  38: tokio::runtime::task::LocalNotified<S>::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  39: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  40: tokio::runtime::coop::with_budget
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  41: tokio::runtime::coop::budget
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  42: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  43: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  44: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  45: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  46: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  47: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  48: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  49: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  50: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  51: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  52: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  53: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  54: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  55: ___rust_try
  56: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  57: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  58: tokio::runtime::task::harness::poll_future
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  59: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  60: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  61: tokio::runtime::task::raw::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  62: tokio::runtime::task::raw::RawTask::poll
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  63: tokio::runtime::task::UnownedTask<S>::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  64: tokio::runtime::blocking::pool::Task::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  65: tokio::runtime::blocking::pool::Inner::run
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  66: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/kuegi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
```
## Steps to Reproduce

Not sure if its only my node or any fresh sync. For me it happens on a fresh sync of changi beta7

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 4.0.0 beta7
- OS with version: MacOS 13.2.1

**Comment by prasannavl** [comment]
The sync issue is due to being on the wrong chain. The initial snapshot the team generated was unfortunately corrupt for beta7 (resulting in that node producing invalid blocks). 

Freshly synced nodes didn't accept that chain. However, was stuck due to a bug that caused the node to think other nodes broadcasting invalid blocks were fatal and shutdown, instead of just ignoring them. This is fixed in https://github.com/DeFiCh/ain/pull/2269

**Comment by kuegi** [comment]
@prasannavl I understand that this happened for block 
`03763d35aa4c326d69fa24535155227b977149bc3852d6545eccc7d9b8460069` which got invalidated and chain switched.
but now it happened again on a new block `0ef56baa54324f51a674ae12dfac3487d9406e9efa60288fd4a38ffc555befc6`. Nodes who where running accepted the block, nodes who didn't run but synced later marked it as invalid. So the current running chain is only accepted by nodes that ran at that time.
Are you sure that this is still due to a wrong snapshot and not an issue with nonce handling during short rollbacks?
